version: 2
updates:
  # Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 10
    assignees:
      - "Mightybeast12"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 5
    assignees:
      - "Mightybeast12"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 3
    assignees:
      - "Mightybeast12"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
