[package]
name = "cv_portfolio_site"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = "0.12.0"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-layout = "0.7.3"
yew-router = { git = "https://github.com/yewstack/yew.git" }


