[package]
name = "cv_portfolio_site"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
gloo-net = "^0.6" 
web-sys = "0.3.70"
pulldown-cmark = "0.12.0"
wasm-bindgen-futures = "0.4.43"
yew-layout = "0.7.3"
yew-router = { git = "https://github.com/yewstack/yew.git" }


