steps:
  # Step 1: Install Rust and Trunk
  - name: 'rust:latest'
    entrypoint: bash
    args:
      - '-c'
      - |
        rustup target add wasm32-unknown-unknown
        cargo install trunk
        trunk build --release
        
  - name: 'cloud-run-source-deploy/cloud-builders/docker'
    args: ['build', '-t', 'cloud-run-source-deploy/$PROJECT_ID/yew-app:$COMMIT_SHA', '.']

  - name: 'cloud-run-source-deploy/cloud-builders/docker'
    args: ['push', 'cloud-run-source-deploy/$PROJECT_ID/yew-app:$COMMIT_SHA']

  - name: 'cloud-run-source-deploy/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - yew-app
      - --image
      - 'cloud-run-source-deploy/$PROJECT_ID/yew-app:$COMMIT_SHA'
      - --region
      - europe=west9
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - 'cloud-run-source-deploy/yew-app:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
