# Rust formatting configuration
# See https://rust-lang.github.io/rustfmt/ for all options

# Basic formatting
edition    = "2021"
max_width  = 100
hard_tabs  = false
tab_spaces = 4

# Import formatting
imports_granularity = "Crate"
group_imports       = "StdExternalCrate"
reorder_imports     = true

# Function formatting
fn_args_layout = "Tall"
brace_style    = "SameLineWhere"

# Control flow formatting
control_brace_style        = "AlwaysSameLine"
match_block_trailing_comma = true

# String formatting
format_strings        = true
format_macro_matchers = true

# Comment formatting
normalize_comments = true
wrap_comments      = true
comment_width      = 80

# Misc formatting
trailing_semicolon   = true
trailing_comma       = "Vertical"
use_small_heuristics = "Default"
newline_style        = "Unix"

# Error handling
error_on_line_overflow = false
error_on_unformatted   = false

# Unstable features (require nightly)
# Uncomment if using nightly Rust
# unstable_features = true
# format_code_in_doc_comments = true
# normalize_doc_attributes = true
