name: Auto-merge minor/patch dependency updates (Dependabot)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  check_suite:
    types: [completed]
  status: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout code for PR analysis
        uses: actions/checkout@v4

      - name: Get PR details and check if it's a major version update
        id: pr-details
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request?.number || context.payload.check_suite?.pull_requests[0]?.number
            });

            console.log('PR Title:', pr.title);
            console.log('PR Body:', pr.body);

            // Check if this is a patch or minor update (not major)
            const isMajorUpdate = pr.title.match(/bump .* from .* to .*\d+\.\d+\.\d+/) &&
                                 pr.body && pr.body.includes('⚠️') && pr.body.includes('BREAKING');

            const isMinorOrPatch = !isMajorUpdate;

            core.setOutput('is-auto-mergeable', isMinorOrPatch);
            core.setOutput('pr-number', pr.number);
            core.setOutput('pr-title', pr.title);

      - name: Wait for all CI checks to pass before auto-merging (max 15 minutes)
        if: steps.pr-details.outputs.is-auto-mergeable == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ steps.pr-details.outputs.pr-number }};

            // Wait for all required checks to complete
            const maxAttempts = 30;
            const delayMs = 30000; // 30 seconds

            for (let attempt = 1; attempt <= maxAttempts; attempt++) {
              console.log(`Attempt ${attempt}/${maxAttempts}: Checking CI status...`);

              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber
              });

              // Get the latest commit SHA
              const commitSha = pr.head.sha;

              // Get all check runs for this commit
              const { data: checkRuns } = await github.rest.checks.listForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: commitSha
              });

              // Get all status checks for this commit
              const { data: statuses } = await github.rest.repos.listCommitStatusesForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: commitSha
              });

              console.log(`Found ${checkRuns.check_runs.length} check runs and ${statuses.length} statuses`);

              // Check if all checks are completed and successful
              const allChecksPassed = checkRuns.check_runs.every(check =>
                check.status === 'completed' && check.conclusion === 'success'
              );

              const allStatusesPassed = statuses.length === 0 || statuses.every(status =>
                status.state === 'success'
              );

              const hasFailedChecks = checkRuns.check_runs.some(check =>
                check.status === 'completed' && ['failure', 'cancelled', 'timed_out'].includes(check.conclusion)
              );

              const hasFailedStatuses = statuses.some(status =>
                ['failure', 'error'].includes(status.state)
              );

              if (hasFailedChecks || hasFailedStatuses) {
                console.log('❌ Some checks failed. Will not auto-merge.');
                core.setFailed('CI checks failed');
                return;
              }

              if (allChecksPassed && allStatusesPassed && checkRuns.check_runs.length > 0) {
                console.log('✅ All CI checks passed!');
                return;
              }

              if (attempt < maxAttempts) {
                console.log(`⏳ Waiting ${delayMs/1000} seconds for checks to complete...`);
                await new Promise(resolve => setTimeout(resolve, delayMs));
              }
            }

            console.log('⏰ Timeout waiting for CI checks to complete');
            core.setFailed('Timeout waiting for CI checks');

      - name: Auto-approve PR after all checks pass
        if: steps.pr-details.outputs.is-auto-mergeable == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ steps.pr-details.outputs.pr-number }};

            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              event: 'APPROVE',
              body: '🤖 Auto-approved by GitHub Actions - all CI checks passed for this dependency update.'
            });

      - name: Merge PR using squash method
        if: steps.pr-details.outputs.is-auto-mergeable == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ steps.pr-details.outputs.pr-number }};

            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'squash',
              commit_title: '${{ steps.pr-details.outputs.pr-title }}',
              commit_message: 'Auto-merged by GitHub Actions after all CI checks passed.'
            });

            console.log('✅ Successfully auto-merged Dependabot PR');

      - name: Generate auto-merge summary report
        if: steps.pr-details.outputs.is-auto-mergeable == 'true' && success()
        run: |
          echo "## ✅ Dependabot PR Auto-Merged Successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📋 PR Details" >> $GITHUB_STEP_SUMMARY
          echo "- **PR Number**: #${{ steps.pr-details.outputs.pr-number }}" >> $GITHUB_STEP_SUMMARY
          echo "- **PR Title**: ${{ steps.pr-details.outputs.pr-title }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Merge Method**: Squash" >> $GITHUB_STEP_SUMMARY
          echo "- **Auto-merged at**: $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🤖 Automation Details" >> $GITHUB_STEP_SUMMARY
          echo "- **Triggered by**: Dependabot" >> $GITHUB_STEP_SUMMARY
          echo "- **Approval**: Automatic (all CI checks passed)" >> $GITHUB_STEP_SUMMARY
          echo "- **Version Type**: Minor/Patch update (non-breaking)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ℹ️ Note" >> $GITHUB_STEP_SUMMARY
          echo "This PR was automatically merged because:" >> $GITHUB_STEP_SUMMARY
          echo "1. It's a minor or patch version update" >> $GITHUB_STEP_SUMMARY
          echo "2. All CI checks passed successfully" >> $GITHUB_STEP_SUMMARY
          echo "3. No breaking changes were detected" >> $GITHUB_STEP_SUMMARY

      - name: Comment on PR to explain why major version updates require manual review
        if: steps.pr-details.outputs.is-auto-mergeable == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ steps.pr-details.outputs.pr-number }};

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: '🚨 **Major version update detected** - This PR was not auto-merged as it contains breaking changes. Please review manually before merging.'
            });

      - name: Generate skip summary for major updates
        if: steps.pr-details.outputs.is-auto-mergeable == 'false'
        run: |
          echo "## ⚠️ Auto-Merge Skipped - Manual Review Required" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📋 PR Details" >> $GITHUB_STEP_SUMMARY
          echo "- **PR Number**: #${{ steps.pr-details.outputs.pr-number }}" >> $GITHUB_STEP_SUMMARY
          echo "- **PR Title**: ${{ steps.pr-details.outputs.pr-title }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🚨 Reason" >> $GITHUB_STEP_SUMMARY
          echo "This appears to be a **major version update** that may contain breaking changes." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📝 Required Actions" >> $GITHUB_STEP_SUMMARY
          echo "1. Review the changelog for breaking changes" >> $GITHUB_STEP_SUMMARY
          echo "2. Test the update in a development environment" >> $GITHUB_STEP_SUMMARY
          echo "3. Update any affected code if necessary" >> $GITHUB_STEP_SUMMARY
          echo "4. Manually approve and merge when ready" >> $GITHUB_STEP_SUMMARY
