jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-approve PR
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
              body: '🤖 Auto-approved by GitHub Actions.'
            });

      - name: Merge PR
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run:
          gh pr merge --squash --auto "${{ github.event.pull_request.html_url
          }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
