name: Auto-merge Dependabot PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto-approve Dependabot PR
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge Dependabot PR
        uses: pascalgn/automerge-action@v0.17.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          commit-message: squash
          merge-when: all-success
