name: Deploy Application

on:
  push:
    branches: [main, test-deploy]
    paths:
      - "Cargo.toml"
      - "src/**"
      - "static/**"
  workflow_dispatch:

env:
  TF_VERSION: "1.5.0"
  TF_WORKING_DIR: "./terraform"

jobs:
  deploy:
    name: "Deploy to Cloud Run"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west9-docker.pkg.dev --quiet

      - name: Terraform Init
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: terraform init

      - name: Deploy Application
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          echo "🚀 Deploying application..."
          terraform apply -auto-approve \
            -target=google_cloud_run_v2_service.portfolio_site \
            -target=null_resource.docker_build \
            -target=null_resource.check_image_exists \
            -var="ci_environment=true" \
            -var="auto_build=true"

      - name: Output URLs
        run: |
          CLOUD_RUN_URL=$(terraform output -raw cloud_run_url)
          CUSTOM_DOMAIN_URL=$(terraform output -raw custom_domain_url)
          
          echo "## 🚀 Deployment Complete!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Application URLs:**" >> $GITHUB_STEP_SUMMARY
          echo "- Custom Domain: $CUSTOM_DOMAIN_URL" >> $GITHUB_STEP_SUMMARY
          echo "- Cloud Run: $CLOUD_RUN_URL" >> $GITHUB_STEP_SUMMARY


